### ISSUE TITLE
failed to load inlined Lua code: access_by_lua

### ISSUE THREAD

**Issue by ChrisJBurns** [openresty/lua-nginx-module#2206]
So we are getting the following error
```logs
[error] 8#8: *446 failed to load inlined Lua code: access_by_lua(nginx.conf:59):6: '<name>' expected near '/', client: 127.0.0.6, server: , request: "GET /api HTTP/1.1", host: "test.our.domain"
```

Running the following versions of modules/images

```dockerfile
FROM imageregistry.domain/bitnami/openresty:1.21.4-1

USER root
RUN apt update && apt install -y curl && apt install -y gettext

RUN opm get ledgetech/lua-resty-http=0.17.1
RUN opm get bungle/lua-resty-session=4.0.4
RUN opm get cdbattags/lua-resty-jwt=0.2.0
RUN opm get zmartzone/lua-resty-openidc=1.7.5

COPY nginx.conf.template nginx.conf.template

USER 1001

ENTRYPOINT envsubst < nginx.conf.template > /opt/bitnami/openresty/nginx/conf/nginx.conf && openresty -g "daemon off;"
```

The nginx.conf that we have:
```lua

events {
    worker_connections 128;
}

http {

    lua_package_path '~/lua/?.lua;;';

    resolver 127.0.0.11;

    # cache for JWT verification results
    lua_shared_dict jwt_verification 10m;

    error_log /dev/stderr;

    server {

        listen ${LISTEN};

        location /test {
            root   /app;
            index  index.html;
        }


         location /api {

            access_by_lua_block {

                local opts = {
                    client_id = ${CLIENT_ID},
                    client_secret = ${CLIENT_SECRET},
                    discovery = ${DISCOVERY_URL},
                    redirect_uri = ${REDIRECT_URL},

                    redirect_uri_scheme = "http",
                    scope = "openid",
                    ssl_verify = "no",
                    keepalive = "yes",
                    use_pkce = true,
                    renew_access_token_on_expiry = true,
                    access_token_expires_leeway = 60,
                    revoke_tokens_on_logout = true
                }

                local res, err = require("resty.openidc").authenticate(opts, nil, "deny")
                local openidc = require("resty.openidc")
                openidc.set_logging(nil, { DEBUG = ngx.DEBUG })

                ngx.log(ngx.STDERR, res)
                ngx.log(ngx.STDERR, err)

                if err or not res then
                    ngx.status = 401
                    ngx.say(err and err or "no access_token provided")
                    ngx.exit(ngx.HTTP_UNAUTHORIZED)
                end
            } # this is the line it's failing on (nginx.conf:59)

            # proxy_pass ${UPSTREAM_URL};
            proxy_pass http://127.0.0.11:3000/test;
        }
```

When we go to the nginx `error.log` and `access.log` we just get this:
```logs
lrwxrwxrwx 1 root root  11 Jun 27 05:08 access.log -> /dev/stdout
lrwxrwxrwx 1 root root  11 Jun 27 05:08 error.log -> /dev/stderr
```

The line that its complaining about when it says `*446 failed to load inlined Lua code: access_by_lua(nginx.conf:59)` is marked as a comment in the above snippet.

The thing to make this to most weird of all, is when I run the above in docker-compose like so:
```yaml
version: "2.4"
services:
  openresty:
    image: ourimgestreg.domain/image:test # redacted but it is the same image that is built using the dockerfile above
    ports:
      - "3000:3000"
    environment:
      - CLIENT_ID="app"
      - CLIENT_SECRET="blah"
      - REDIRECT_URL="blah"
      - DISCOVERY_URL="blah"
      - UPSTREAM_URL="http://blah.com"
      - SESSION_SECRET="secretsecretsecret"
      - LISTEN="3000"
```

And I curl the endpoint with `curl localhost:3000/api` i get the unauthorised error. But when I access it when it is deployed into the cluster, I get the error around `access_by_lua(nginx.conf:59)`. This has really baffled me, I'm using the same image, same environment variables, and I'm getting completely different outcomes. I'm not a lua expert at all, in fact, this is the first time I've ever had to use it, but the fact that it works locally but not in k8s is the thing that completely stumps me.
